# fly.toml app configuration file updated for my-mysql-amby-2 on 2024-05-20

app = "my-mysql-amby-2"
primary_region = "ewr"

[build]
  image = "mysql:8"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[services]
  [[services.ports]]
    handlers = ["tcp"]
    port = "3306"

[processes]
  app = "--datadir /data/mysql --default-authentication-plugin=mysql_native_password"

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"
  MYSQL_PASSWORD = "password"
  MYSQL_ROOT_PASSWORD = "password"
